<a href="https://colab.research.google.com/github/BrendJ510/Terminal_Economia/blob/Proyecto_Economia_III/EjerciciosdeClase_EconomiaIII.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Ejercicios de estructuras

In [ ]:
ciudades = ["Queretaro","Monterrey","Guadalajara","Puebla","Tijuana"]
ciudades.extend(["Cancún","Ciudad de México"])
print(ciudades)
ciudades.sort()
ciudades.remove('Puebla')
print(ciudades)

['Queretaro', 'Monterrey', 'Guadalajara', 'Puebla', 'Tijuana', 'Cancún', 'Ciudad de México']
['Cancún', 'Ciudad de México', 'Guadalajara', 'Monterrey', 'Queretaro', 'Tijuana']


In [ ]:
numeros = (3,8,15,22,7)
numero = list(numeros)
numero.append(10)
print(numero)
numero.sort(reverse=True)

[3, 8, 15, 22, 7, 10]


In [ ]:
# Definiendo los conjuntos A y B OPERACIONES CON CONJUNTOS
A = {"manzana", "pera", "uvas", "mango"}
B = {"pera", "mango", "piña", "sandía"}

# Unión de A y B
union = A.union(B)
print("Unión de A y B:", union)

# Intersección de A y B
interseccion = A.intersection(B)
print("Intersección de A y B:", interseccion)

# Diferencia de A con respecto a B
diferencia = A.difference(B)
print("Diferencia de A con respecto a B:", diferencia)

# Verificar si "uvas" está en el conjunto B
uvas_en_B = "uvas" in B
print("¿Está 'uvas' en el conjunto B?", uvas_en_B)


Unión de A y B: {'uvas', 'mango', 'piña', 'pera', 'sandía', 'manzana'}
Intersección de A y B: {'mango', 'pera'}
Diferencia de A con respecto a B: {'uvas', 'manzana'}
¿Está 'uvas' en el conjunto B? False


In [ ]:
# Diccionario de inventario inicial
inventario = {"laptops": 10, "teclados": 25, "mouse": 50}

# Agregar el producto "monitores" con un valor inicial de 15
inventario["monitores"] = 15

# Modificar el valor de "laptops" a 8
inventario["laptops"] = 8

# Eliminar "mouse" del inventario
del inventario["mouse"]

# Imprimir el inventario actualizado
print("Inventario actualizado:", inventario)


Inventario actualizado: {'laptops': 8, 'teclados': 25, 'monitores': 15}


In [ ]:
# Dada la cadena
frase = "Python es un lenguaje poderoso y versátil"

# Convertir la cadena a mayúsculas
frase_mayusculas = frase.upper()
print("Cadena en mayúsculas:", frase_mayusculas)

# Reemplazar la palabra "poderoso" por "popular"
frase_reemplazada = frase.replace("poderoso", "popular")
print("Cadena con reemplazo:", frase_reemplazada)

# Dividir la cadena en una lista de palabras
lista_palabras = frase.split()
print("Lista de palabras:", lista_palabras)

# Encontrar cuántas veces aparece la letra "e"
conteo_e = frase.count("e")
print("Número de veces que aparece la letra 'e':", conteo_e)



Cadena en mayúsculas: PYTHON ES UN LENGUAJE PODEROSO Y VERSÁTIL
Cadena con reemplazo: Python es un lenguaje popular y versátil
Lista de palabras: ['Python', 'es', 'un', 'lenguaje', 'poderoso', 'y', 'versátil']
Número de veces que aparece la letra 'e': 5


In [ ]:
# Lista de palabras
palabras = ["python", "código", "datos", "python", "análisis", "datos", "código"]

# Crear un diccionario para contar las apariciones de cada palabra
conteo_palabras = {}
for palabra in palabras:
    if palabra in conteo_palabras:
        conteo_palabras[palabra] += 1
    else:
        conteo_palabras[palabra] = 1

# Encontrar la palabra más repetida
palabra_mas_repetida = max(conteo_palabras, key=conteo_palabras.get)

# Imprimir el diccionario resultante
print("Diccionario de conteo de palabras:", conteo_palabras)
print("Palabra más repetida:", palabra_mas_repetida)


Diccionario de conteo de palabras: {'python': 2, 'código': 2, 'datos': 2, 'análisis': 1}
Palabra más repetida: python


In [ ]:
# Diccionario de personajes inicial
personajes = {
    "guerrero": {"fuerza": 80, "salud": 100},
    "arquero": {"fuerza": 65, "salud": 80},
    "mago": {"fuerza": 50, "salud": 60},
}

# Agregar un nuevo personaje "hechicero" con fuerza: 70 y salud: 85
personajes["hechicero"] = {"fuerza": 70, "salud": 85}

# Incrementar la fuerza del "arquero" en 10 puntos
personajes["arquero"]["fuerza"] += 10

# Encontrar el personaje con mayor salud
personaje_mayor_salud = max(personajes, key=lambda x: personajes[x]["salud"])

# Imprimir el diccionario actualizado y el personaje con mayor salud
print("Diccionario actualizado de personajes:", personajes)
print("Personaje con mayor salud:", personaje_mayor_salud)


Diccionario actualizado de personajes: {'guerrero': {'fuerza': 80, 'salud': 100}, 'arquero': {'fuerza': 75, 'salud': 80}, 'mago': {'fuerza': 50, 'salud': 60}, 'hechicero': {'fuerza': 70, 'salud': 85}}
Personaje con mayor salud: guerrero


In [ ]:
# Diccionario de cuentas inicial
cuentas = {
    "1234": {"titular": "Juan", "saldo": 5000},
    "5678": {"titular": "Ana", "saldo": 7000},
    "9101": {"titular": "Luis", "saldo": 3000},
}

# Realizar un depósito de 1000 a la cuenta "1234"
cuentas["1234"]["saldo"] += 1000

# Retirar 2000 de la cuenta "5678"
cuentas["5678"]["saldo"] -= 2000

# Calcular el saldo total del banco sumando todas las cuentas
saldo_total = sum(cuenta["saldo"] for cuenta in cuentas.values())

# Imprimir el saldo total del banco
print("Saldo total del banco:", saldo_total)


Saldo total del banco: 14000


In [ ]:
# Dada la cadena de texto
frase = "El análisis de datos es esencial en el mundo actual"

# Dividir la cadena en una lista de palabras
palabras = frase.split()

# Convertir todas las palabras a minúsculas
palabras = [palabra.lower() for palabra in palabras]

# Encontrar la palabra más larga y más corta
palabra_mas_larga = max(palabras, key=len)
palabra_mas_corta = min(palabras, key=len)

# Contar cuántas palabras contienen la letra "a"
palabras_con_a = [palabra for palabra in palabras if "a" in palabra]
conteo_palabras_con_a = len(palabras_con_a)

# Ordenar las palabras alfabéticamente
palabras_ordenadas = sorted(palabras)

# Mostrar los resultados
print("Palabra más larga:", palabra_mas_larga)
print("Palabra más corta:", palabra_mas_corta)
print("Número de palabras que contienen la letra 'a':", conteo_palabras_con_a)
print("Lista de palabras ordenadas alfabéticamente:", palabras_ordenadas)



Palabra más larga: análisis
Palabra más corta: el
Número de palabras que contienen la letra 'a': 4
Lista de palabras ordenadas alfabéticamente: ['actual', 'análisis', 'datos', 'de', 'el', 'el', 'en', 'es', 'esencial', 'mundo']


In [ ]:
# Dado el inventario
inventario = {"manzanas": 50, "naranjas": 35, "plátanos": 20}

# Crear un conjunto con los productos agotados (cantidad igual a 0)
productos_agotados = {producto for producto, cantidad in inventario.items() if cantidad == 0}

# Calcular el total de productos disponibles
total_productos_disponibles = sum(inventario.values())

# Encontrar el producto con mayor cantidad disponible
producto_mayor_cantidad = max(inventario, key=inventario.get)

# Mostrar los resultados
print("Productos agotados:", productos_agotados)
print("Total de productos disponibles:", total_productos_disponibles)
print("Producto con mayor cantidad disponible:", producto_mayor_cantidad)


Productos agotados: set()
Total de productos disponibles: 105
Producto con mayor cantidad disponible: manzanas


#Ejercicios de Funciones

In [ ]:
def calculadora():
    while True:
        try:
            # Solicitar los números al usuario
            num1 = float(input("Introduce el primer número: "))
            num2 = float(input("Introduce el segundo número: "))

            # Solicitar la operación al usuario
            operacion = input("Introduce la operación (+, -, *, /, **, %): ")

            if operacion == '+':
                return num1 + num2
            elif operacion == '-':
                return num1 - num2
            elif operacion == '*':
                return num1 * num2
            elif operacion == '/':
                if num2 == 0:
                    raise ZeroDivisionError("No se puede dividir entre cero.")
                return num1 / num2
            elif operacion == '**':
                return num1 ** num2
            elif operacion == '%':
                return num1 % num2
            else:
                raise ValueError("Operación no válida.")
        except ValueError as e:
            print(f"Error: {e}. Inténtalo de nuevo.")
        except ZeroDivisionError as e:
            print(f"Error: {e}. Inténtalo de nuevo.")

# Ejecutar la función
resultado = calculadora()
print("Resultado:", resultado)



Introduce el primer número: k
Error: could not convert string to float: 'k'. Inténtalo de nuevo.
Introduce el primer número: 9
Introduce el segundo número: 89
Introduce la operación (+, -, *, /, **, %): ,
Error: Operación no válida.. Inténtalo de nuevo.
Introduce el primer número: 2
Introduce el segundo número: 3
Introduce la operación (+, -, *, /, **, %): +
Resultado: 5.0


In [ ]:
def convertir_temperatura():
    try:
        # Solicitar la temperatura y las unidades al usuario
        temperatura = float(input("Introduce la temperatura: "))
        unidad_origen = input("Introduce la unidad de origen (C, F, K): ").upper()
        unidad_destino = input("Introduce la unidad de destino (C, F, K): ").upper()

        # Validar la unidad de origen
        if unidad_origen not in ['C', 'F', 'K']:
            raise ValueError("Unidad de origen no válida.")
        # Validar la unidad de destino
        if unidad_destino not in ['C', 'F', 'K']:
            raise ValueError("Unidad de destino no válida.")
        # Evitar temperaturas Kelvin negativas
        if unidad_origen == 'K' and temperatura < 0:
            raise ValueError("La temperatura en Kelvin no puede ser negativa.")

        # Realizar la conversión
        if unidad_origen == 'C':
            if unidad_destino == 'F':
                resultado = (temperatura * 9/5) + 32
            elif unidad_destino == 'K':
                resultado = temperatura + 273.15
            else:
                resultado = temperatura
        elif unidad_origen == 'F':
            if unidad_destino == 'C':
                resultado = (temperatura - 32) * 5/9
            elif unidad_destino == 'K':
                resultado = (temperatura - 32) * 5/9 + 273.15
            else:
                resultado = temperatura
        elif unidad_origen == 'K':
            if unidad_destino == 'C':
                resultado = temperatura - 273.15
            elif unidad_destino == 'F':
                resultado = (temperatura - 273.15) * 9/5 + 32
            else:
                resultado = temperatura

        return f"La temperatura convertida es: {resultado:.2f} {unidad_destino}"

    except ValueError as e:
        print(f"Error: {e}. Inténtalo de nuevo.")

# Ejecutar la función
resultado = convertir_temperatura()
print(resultado)


Introduce la temperatura: 12
Introduce la unidad de origen (C, F, K): C
Introduce la unidad de destino (C, F, K): C
La temperatura convertida es: 12.00 C


In [ ]:
import random
import string

def generar_contraseña():
    try:
        # Solicitar la longitud de la contraseña al usuario
        longitud = int(input("Introduce la longitud de la contraseña (mínimo 6): "))

        # Verificar que la longitud sea válida
        if longitud < 6:
            raise ValueError("La longitud debe ser al menos 6.")

        # Caracteres permitidos en la contraseña
        caracteres = string.ascii_letters + string.digits + string.punctuation

        # Generar la contraseña aleatoria
        contraseña = ''.join(random.choice(caracteres) for _ in range(longitud))

        return contraseña

    except ValueError as e:
        print(f"Error: {e}. Inténtalo de nuevo.")
        return generar_contraseña()

# Ejecutar la función
contraseña = generar_contraseña()
print("Contraseña generada:", contraseña)


Introduce la longitud de la contraseña (mínimo 6): 9
Contraseña generada: rglSkPNi-


In [ ]:


def calcular_estadisticas():
    try:
        # Solicitar la lista de números al usuario
        lista = input("Introduce una lista de números separados por comas: ").split(',')

        # Convertir los elementos a números
        lista = [float(elemento) for elemento in lista]

        if not lista:
            raise ValueError("La lista está vacía.")

        # Calcular el promedio
        promedio = sum(lista) / len(lista)

        # Encontrar el número más grande y el más pequeño
        num_max = max(lista)
        num_min = min(lista)

        # Calcular la mediana
        lista_ordenada = sorted(lista)
        n = len(lista_ordenada)
        if n % 2 == 1:
            mediana = lista_ordenada[n // 2]
        else:
            mediana = (lista_ordenada[n // 2 - 1] + lista_ordenada[n // 2]) / 2

        return promedio, num_max, num_min, mediana

    except ValueError as e:
        return f"Error: {e}"

# Ejecutar la función
estadisticas = calcular_estadisticas()
if isinstance(estadisticas, str):
    print(estadisticas)  # Imprimir error si hay
else:
    promedio, num_max, num_min, mediana = estadisticas
    print("Promedio:", promedio)
    print("Número más grande:", num_max)
    print("Número más pequeño:", num_min)
    print("Mediana:", mediana)


Introduce una lista de números separados por comas: 12,3,5,7,8
Promedio: 7.0
Número más grande: 12.0
Número más pequeño: 3.0
Mediana: 7.0


In [ ]:
def validar_usuario_y_contraseña():
    try:
        # Solicitar el nombre de usuario y la contraseña al usuario
        usuario = input("Introduce el nombre de usuario: ")
        contraseña = input("Introduce la contraseña: ")

        # Verificar que las entradas no estén vacías
        if not usuario or not contraseña:
            raise ValueError("El usuario o la contraseña no pueden estar vacíos.")

        # Verificar que el usuario tenga al menos 5 caracteres
        if len(usuario) < 5:
            raise ValueError("El usuario debe tener al menos 5 caracteres.")

        # Verificar que la contraseña tenga al menos 8 caracteres
        if len(contraseña) < 8:
            raise ValueError("La contraseña debe tener al menos 8 caracteres.")

        # Verificar que la contraseña incluya al menos un número y una mayúscula
        if not any(char.isdigit() for char in contraseña):
            raise ValueError("La contraseña debe incluir al menos un número.")
        if not any(char.isupper() for char in contraseña):
            raise ValueError("La contraseña debe incluir al menos una mayúscula.")

        return "Usuario y contraseña válidos."

    except ValueError as e:
        print(f"Error: {e}. Inténtalo de nuevo.")
        return validar_usuario_y_contraseña()

# Ejecutar la función
resultado = validar_usuario_y_contraseña()
print(resultado)


Introduce el nombre de usuario: brenda
Introduce la contraseña: jimenez2
Error: La contraseña debe incluir al menos una mayúscula.. Inténtalo de nuevo.
Introduce el nombre de usuario: brenda
Introduce la contraseña: Jimenez2
Usuario y contraseña válidos.


#Ejercicios de modulo y librerías

In [ ]:
# Importamos la librería math
import math

# Solicitamos los valores al usuario
P = float(input("Ingresa el capital inicial (P): "))
r = float(input("Ingresa la tasa de interés anual (r) en decimal (ejemplo 5% = 0.05): "))
n = int(input("Ingresa el número de veces que se capitaliza en un año (mensual = 12, trimestral = 4, anual = 1): "))
t = int(input("Ingresa el número de años (t): "))

# Calculamos el interés compuesto
A = P * math.pow((1 + r / n), n * t)

# Mostramos el resultado con 2 decimales
print(f"El monto total después de {t} años es: ${A:.2f}")


Ingresa el capital inicial (P): 100
Ingresa la tasa de interés anual (r) en decimal (ejemplo 5% = 0.05): 0.05
Ingresa el número de veces que se capitaliza en un año (mensual = 12, trimestral = 4, anual = 1): 1
Ingresa el número de años (t): 3
El monto total después de 3 años es: $115.76


In [ ]:
r =float(input('ingresa el radio r de la esfera: '))

#Área:
A = 4 * math.pi * math.pow(r,2)
print(f'El área de la esfera es: {A:.3f}')
V= 4/3 * math.pi * math.pow(r,3)
print(f'El volumen de la esfera es: {V:.3f}')

ingresa el radio r de la esfera: 8
El área de la esfera es: 804.248
El volumen de la esfera es: 2144.661


In [ ]:
# Importamos la librería random
import random

# Definimos el precio inicial
precio_inicial = 100

# Inicializamos la lista de precios con el precio inicial
precios = [precio_inicial]

# Generamos 10 precios posteriores
for _ in range(10):
    # Definimos la variación aleatoria entre -5% y +5%
    variacion = random.uniform(-0.05, 0.05)
    # Calculamos el nuevo precio
    nuevo_precio = precios[-1] * (1 + variacion)
    # Agregamos el nuevo precio a la lista
    precios.append(nuevo_precio)

# Imprimimos la lista de precios
print("Simulación de precios de la acción:")
for precio in precios:
    print(f"${precio:.2f}")


Simulación de precios de la acción:
$100.00
$98.97
$94.94
$99.09
$101.82
$101.37
$106.15
$105.27
$100.10
$95.10
$95.13


In [ ]:
# Importamos la librería random
import random

# Generamos 10 valores aleatorios entre 1 y 6
lanzamientos = [random.randint(1, 6) for _ in range(10)]

# Contamos cuántas veces salió cada número (1 a 6)
resultados = {i: lanzamientos.count(i) for i in range(1, 7)}

# Imprimimos los resultados de la simulación
print("Resultados de la simulación de lanzamientos de dado:")
for numero, conteo in resultados.items():
    print(f"Número {numero}: {conteo} veces")


Resultados de la simulación de lanzamientos de dado:
Número 1: 1 veces
Número 2: 0 veces
Número 3: 3 veces
Número 4: 0 veces
Número 5: 4 veces
Número 6: 2 veces


In [ ]:
import random
import string

def generar_contraseña_segura(longitud=12):
    # Conjuntos de caracteres permitidos
    caracteres = string.ascii_letters + string.digits + string.punctuation

    # Generar la contraseña aleatoria
    contraseña = ''.join(random.choice(caracteres) for _ in range(longitud))

    return contraseña

# Generar y imprimir la contraseña segura
contraseña = generar_contraseña_segura()
print("Contraseña segura generada:", contraseña)


Contraseña segura generada: 3B1ioB+u>J;:


In [ ]:
import datetime

def calcular_fecha_vencimiento():
    try:
        # Solicitar la fecha de inicio al usuario
        fecha_inicio_str = input("Introduce la fecha de inicio (YYYY-MM-DD): ")
        fecha_inicio = datetime.datetime.strptime(fecha_inicio_str, "%Y-%m-%d")

        # Solicitar el número de días que durará el plazo fijo
        dias_plazo_fijo = int(input("Introduce el número de días que durará el plazo fijo: "))

        # Calcular la fecha de vencimiento
        fecha_vencimiento = fecha_inicio + datetime.timedelta(days=dias_plazo_fijo)

        # Imprimir la fecha de vencimiento en el formato "DD de Mes de YYYY"
        fecha_vencimiento_formato = fecha_vencimiento.strftime("%d de %B de %Y")
        print("La fecha de vencimiento es:", fecha_vencimiento_formato)

    except ValueError as e:
        print(f"Error: {e}. Asegúrate de ingresar la fecha y los días correctamente.")

# Ejecutar la función
calcular_fecha_vencimiento()


Introduce la fecha de inicio (YYYY-MM-DD): 2025-08-22
Introduce el número de días que durará el plazo fijo: 5
La fecha de vencimiento es: 27 de August de 2025


In [ ]:
import datetime

# Solicitar al usuario las dos fechas en formato YYYY-MM-DD
fecha1_str = input("Introduce la primera fecha (YYYY-MM-DD): ")
fecha2_str = input("Introduce la segunda fecha (YYYY-MM-DD): ")

# Convertir las cadenas a objetos datetime
fecha1 = datetime.datetime.strptime(fecha1_str, "%Y-%m-%d")
fecha2 = datetime.datetime.strptime(fecha2_str, "%Y-%m-%d")

# Calcular la diferencia en días
diferencia = fecha2 - fecha1
dias_transcurridos = diferencia.days

# Mostrar la cantidad de días transcurridos
print(f"Han pasado {dias_transcurridos} días entre {fecha1_str} y {fecha2_str}.")


Introduce la primera fecha (YYYY-MM-DD): 2003-05-10
Introduce la segunda fecha (YYYY-MM-DD): 2021-07-21
Han pasado 6647 días entre 2003-05-10 y 2021-07-21.


In [ ]:
import random

# Pedir al usuario que ingrese la cantidad de participantes
while True:
    num_participantes = int(input("¿Cuántos participantes vas a ingresar? (mínimo 5): "))
    if num_participantes >= 5:
        break
    else:
        print("Necesitas ingresar al menos 5 participantes.")

# Pedir al usuario que ingrese los nombres de los participantes
nombres = []
print(f"Introduce los nombres de los {num_participantes} participantes:")
for _ in range(num_participantes):
    nombre = input("Nombre: ")
    nombres.append(nombre)

# Usar random.choice() para elegir un ganador
ganador = random.choice(nombres)

# Imprimir el nombre del ganador
print(f"El ganador del sorteo es: {ganador}")




¿Cuántos participantes vas a ingresar? (mínimo 5): 5
Introduce los nombres de los 5 participantes:
Nombre: gaby
Nombre: jess
Nombre: jesus
Nombre: sus
Nombre: je
El ganador del sorteo es: gaby


In [ ]:
import math

# Pedir al usuario el monto que ahorrará cada mes
monto_mensual = float(input("Introduce el monto que ahorrarás cada mes: "))

# Pedir al usuario el número de meses que planea ahorrar
meses = int(input("Introduce el número de meses que planeas ahorrar: "))

# Pedir al usuario la tasa de interés anual (en porcentaje)
tasa_interes_anual = float(input("Introduce la tasa de interés anual (en %): "))

# Convertir la tasa de interés anual a una tasa mensual
tasa_interes_mensual = (tasa_interes_anual / 100) / 12

# Calcular el monto total ahorrado usando la fórmula del interés compuesto
monto_total = monto_mensual * ((math.pow(1 + tasa_interes_mensual, meses) - 1) / tasa_interes_mensual) * (1 + tasa_interes_mensual)

# Mostrar el resultado con dos decimales
print(f"El monto total ahorrado después de {meses} meses es: ${monto_total:.2f}")


Introduce el monto que ahorrarás cada mes: 100
Introduce el número de meses que planeas ahorrar: 3
Introduce la tasa de interés anual (en %): 12
El monto total ahorrado después de 3 meses es: $306.04


In [ ]:
import datetime

# Pedir al usuario la fecha del último pago en formato YYYY-MM-DD
fecha_ultimo_pago_str = input("Introduce la fecha del último pago (YYYY-MM-DD): ")

# Convertir la cadena a un objeto datetime
fecha_ultimo_pago = datetime.datetime.strptime(fecha_ultimo_pago_str, "%Y-%m-%d")

# Calcular la fecha del próximo pago sumando 30 días
fecha_proximo_pago = fecha_ultimo_pago + datetime.timedelta(days=30)

# Formatear la nueva fecha en "DD de Mes de YYYY"
fecha_proximo_pago_formateada = fecha_proximo_pago.strftime("%d de %B de %Y")

# Mostrar la nueva fecha
print(f"La fecha del próximo pago es: {fecha_proximo_pago_formateada}")


Introduce la fecha del último pago (YYYY-MM-DD): 2024-04-02
La fecha del próximo pago es: 02 de May de 2024


#Ejercicio Numpy

In [ ]:
import numpy as np

# Crear el array con los valores dados
arr = np.array([10, 20, 30, 40, 50])

# Multiplicar cada elemento por 2
arr = arr * 2

# Sumar 5 a cada elemento
arr = arr + 5

# Calcular la media, mediana y desviación estándar del array
media = np.mean(arr)
mediana = np.median(arr)
desviacion_estandar = np.std(arr)

# Mostrar los resultados
print(f"Array resultante: {arr}")
print(f"Media: {media}")
print(f"Mediana: {mediana}")
print(f"Desviación estándar: {desviacion_estandar}")


Array resultante: [ 25  45  65  85 105]
Media: 65.0
Mediana: 65.0
Desviación estándar: 28.284271247461902


In [ ]:
import numpy as np

# Crear el array bidimensional
matriz = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

# Extraer la segunda fila
segunda_fila = matriz[1, :]
print(f"Segunda fila: {segunda_fila}")

# Extraer la tercera columna
tercera_columna = matriz[:, 2]
print(f"Tercera columna: {tercera_columna}")

# Obtener la submatriz de los elementos [2,3], [5,6]
submatriz = matriz[0:2, 1:3]
print(f"Submatriz:\n{submatriz}")


Segunda fila: [4 5 6]
Tercera columna: [3 6 9]
Submatriz:
[[2 3]
 [5 6]]


In [ ]:
import numpy as np

# Definir las matrices
A = np.array([[2, 3], [1, 4]])
B = np.array([[5, 2], [3, 1]])

# Calcular la suma A + B
suma = A + B
print(f"Suma A + B:\n{suma}\n")

# Calcular la resta A - B
resta = A - B
print(f"Resta A - B:\n{resta}\n")

# Multiplicar cada elemento de A por 3
multiplicacion = A * 3
print(f"Multiplicación de cada elemento de A por 3:\n{multiplicacion}\n")

# Obtener la traspuesta de B
traspuesta_B = B.T
print(f"Traspuesta de B:\n{traspuesta_B}\n")


Suma A + B:
[[7 5]
 [4 5]]

Resta A - B:
[[-3  1]
 [-2  3]]

Multiplicación de cada elemento de A por 3:
[[ 6  9]
 [ 3 12]]

Traspuesta de B:
[[5 3]
 [2 1]]



In [ ]:
import numpy as np

# Definir los vectores
v1 = np.array([2, 4, -1])
v2 = np.array([5, -3, 2])

# Calcular el producto punto entre v1 y v2
producto_punto = np.dot(v1, v2)
print(f"Producto punto entre v1 y v2: {producto_punto}")

# Calcular el producto cruz entre v1 y v2
producto_cruz = np.cross(v1, v2)
print(f"Producto cruz entre v1 y v2:\n{producto_cruz}")


Producto punto entre v1 y v2: -4
Producto cruz entre v1 y v2:
[  5  -9 -26]


In [ ]:
import numpy as np

# Definir el vector
v = np.array([3, -4, 1])

# Calcular la norma Euclidiana (L2)
norma_L2 = np.linalg.norm(v)
print(f"Norma Euclidiana (L2): {norma_L2}")

# Calcular la norma Manhattan (L1)
norma_L1 = np.sum(np.abs(v))
print(f"Norma Manhattan (L1): {norma_L1}")

# Calcular la norma Máxima (L∞)
norma_Linf = np.max(np.abs(v))
print(f"Norma Máxima (L∞): {norma_Linf}")


Norma Euclidiana (L2): 5.0990195135927845
Norma Manhattan (L1): 8
Norma Máxima (L∞): 4


In [ ]:
import numpy as np

# Definir la matriz
M = np.array([[4, 7],
              [2, 6]])

# Calcular el determinante de la matriz
determinante = np.linalg.det(M)
print(f"Determinante de M: {determinante}")

# Obtener la matriz inversa de M
inversa = np.linalg.inv(M)
print(f"Matriz inversa de M:\n{inversa}")

# Calcular los eigenvalores y eigenvectores de M
eigenvalores, eigenvectores = np.linalg.eig(M)
print(f"Eigenvalores de M: {eigenvalores}")
print(f"Eigenvectores de M:\n{eigenvectores}")


Determinante de M: 10.000000000000002
Matriz inversa de M:
[[ 0.6 -0.7]
 [-0.2  0.4]]
Eigenvalores de M: [1.12701665 8.87298335]
Eigenvectores de M:
[[-0.92511345 -0.82071729]
 [ 0.37969079 -0.57133452]]


In [ ]:
import numpy as np

# Crear una matriz identidad de tamaño 4x4
matriz_identidad = np.eye(4)
print("Matriz identidad de tamaño 4x4:")
print(matriz_identidad)

# Crear una matriz de ceros de tamaño 3x3
matriz_ceros = np.zeros((3, 3))
print("\nMatriz de ceros de tamaño 3x3:")
print(matriz_ceros)

# Crear una matriz de unos de tamaño 5x5
matriz_unos = np.ones((5, 5))
print("\nMatriz de unos de tamaño 5x5:")
print(matriz_unos)

# Crear una matriz aleatoria de números entre 0 y 1 con tamaño 2x3
matriz_aleatoria = np.random.rand(2, 3)
print("\nMatriz aleatoria de números entre 0 y 1 con tamaño 2x3:")
print(matriz_aleatoria)


Matriz identidad de tamaño 4x4:
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]

Matriz de ceros de tamaño 3x3:
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]

Matriz de unos de tamaño 5x5:
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]

Matriz aleatoria de números entre 0 y 1 con tamaño 2x3:
[[0.72760165 0.0841893  0.66955386]
 [0.81095566 0.39904748 0.13610076]]


In [ ]:
import numpy as np

# Crear un array de 10 valores aleatorios simulando los precios de una acción entre 100 y 200
precios = np.random.uniform(100, 200, 10)
print(f"Precios de la acción: {precios}")

# Calcular el promedio de precios y su desviación estándar
promedio_precios = np.mean(precios)
desviacion_estandar_precios = np.std(precios)
print(f"Promedio de precios: {promedio_precios:.2f}")
print(f"Desviación estándar de precios: {desviacion_estandar_precios:.2f}")

# Obtener la variación diaria de precios
variacion_diaria = np.diff(precios)
print(f"Variación diaria de precios: {variacion_diaria}")


Precios de la acción: [135.77128965 114.33048372 143.06183587 162.47553489 126.22843574
 124.14358305 171.39355053 141.8108237  194.93020813 198.02042885]
Promedio de precios: 151.22
Desviación estándar de precios: 27.83
Variación diaria de precios: [-21.44080593  28.73135215  19.41369902 -36.24709915  -2.08485269
  47.24996748 -29.58272683  53.11938443   3.09022072]


In [ ]:
import numpy as np

# Datos de precios de las acciones
precios_A = np.array([100, 102, 105, 103, 108, 110])
precios_B = np.array([95, 97, 96, 94, 99, 101])

# Calcular la covarianza entre ambos activos
covarianza = np.cov(precios_A, precios_B)[0, 1]
print(f"Covarianza entre ambos activos: {covarianza}")

# Calcular la correlación de Pearson entre ambos activos
correlacion_pearson = np.corrcoef(precios_A, precios_B)[0, 1]
print(f"Correlación de Pearson entre ambos activos: {correlacion_pearson}")


Covarianza entre ambos activos: 8.4
Correlación de Pearson entre ambos activos: 0.8528321668316973


In [ ]:
import numpy as np

# Rendimientos esperados de las acciones
rendimientos = np.array([0.05, 0.02, 0.07, 0.03])

# Pesos de las acciones en el portafolio
pesos = np.array([0.4, 0.2, 0.3, 0.1])

# Calcular el rendimiento esperado del portafolio
rendimiento_esperado_portafolio = np.sum(rendimientos * pesos)
print(f"Rendimiento esperado del portafolio: {rendimiento_esperado_portafolio:.4f}")

# Supongamos una matriz de covarianza (ejemplo ficticio)
matriz_covarianza = np.array([
    [0.0004, 0.0001, 0.0002, 0.0001],
    [0.0001, 0.0003, 0.0001, 0.0001],
    [0.0002, 0.0001, 0.0005, 0.0002],
    [0.0001, 0.0001, 0.0002, 0.0004]
])

# Calcular la varianza del portafolio
varianza_portafolio = np.dot(pesos.T, np.dot(matriz_covarianza, pesos))
volatilidad_portafolio = np.sqrt(varianza_portafolio)
print(f"Volatilidad del portafolio: {volatilidad_portafolio:.4f}")


Rendimiento esperado del portafolio: 0.0480
Volatilidad del portafolio: 0.0150
